### ISSUE TITLE
Crashes when loading into world (1.17)

### ISSUE THREAD

**Issue by legosteenjaap** [KdotJPG/Simply-Improved-Terrain#13]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/07/2021, 09:28
Description: Exception initializing level

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_2806.method_16565(class_2806.java:64)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:275)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)
	at net.minecraft.class_3898.method_17225(class_3898.java:556)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [simplyimprovedterrain.mixins.json:MixinChunkRegion] from phase [DEFAULT] in config [simplyimprovedterrain.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injectConstructor could not find any targets matching 'Lnet/minecraft/class_3233;<init>(Lnet/minecraft/class_3218;Ljava/util/List;)V' in net.minecraft.class_3233. Using refmap SimplyImprovedTerrain-refmap.json [PREINJECT Applicator Phase -> simplyimprovedterrain.mixins.json:MixinChunkRegion -> Prepare Injections ->  -> handler$zfi000$injectConstructor(Lnet/minecraft/class_3218;Ljava/util/List;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor58.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_2806.method_16565(class_2806.java:64)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:275)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)
	at net.minecraft.class_3898.method_17225(class_3898.java:556)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:550)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (24,64,152), Section: (at 8,0,8 in 1,4,9; chunk contains blocks 16,0,144 to 31,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:401)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350)
	at net.minecraft.class_1132.method_3823(class_1132.java:71)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, GraalVM Community
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), GraalVM Community
	Memory: 3473947504 bytes (3313 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 17 Stepping 0
	Microarchitecture: Zen
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6677
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23571.14
	Virtual memory used (MB): 18341.47
	Swap memory total (MB): 7240.24
	Swap memory used (MB): 175.19
	JVM Flags: 7 total; -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:ThreadPriorityPolicy=1 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m
	Fabric Mods: 
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab612113
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c13
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		simplyimprovedterrain: Simply Improved Terrain 0.4-Fabric-1.17
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by KdotJPG** [comment]
Seems I didn't use a new enough version for my versions in the gradle properties file. Updating and making corresponding code changes to see if I can get this resolved shortly!

**Comment by legosteenjaap** [comment]
Epic!

**Comment by KdotJPG** [comment]
Resolved! Uploaded on Curseforge now https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain-fabric/files/3387213
