### ISSUE TITLE
[Server crash] Crash during server start -possibly related to mods changing 1.18s world height feature-

### ISSUE THREAD

**Issue by Andyghandi** [KdotJPG/Simply-Improved-Terrain#14]
Fabric Version: 0.11.6-1.17
SIT version: 0.4.0.1
Charm version: 3.3.0
Repurposed structures version: 2.1.0

After Adding this mod to my server, it crashes. 
The crash log hints there is something to do with this mod and charm. I guess charms way of implementing structures isn't working properly with this mod, but I could be wrong.

Relevant crash report material:

Description: Exception generating new chunk

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 384
	at jpg.k.simplyimprovedterrain.terrain.SimplyImprovedNoiseColumnSampler.applyThresholdSlides(SimplyImprovedNoiseColumnSampler.java:132)
	at jpg.k.simplyimprovedterrain.terrain.SimplyImprovedNoiseColumnSampler$ColumnSamplingContext.sampleNoiseSign(SimplyImprovedNoiseColumnSampler.java:110)
	at net.minecraft.class_3754.handler$zik000$sampleHeightmap(class_3754.java:2818)
	at net.minecraft.class_3754.method_26263(class_3754.java)
	at net.minecraft.class_3754.method_26261(class_3754.java:208)
	at svenhjol.charm.module.biome_dungeons.DungeonFeature$Start.generatePieces(DungeonFeature.java:65)
	at svenhjol.charm.module.biome_dungeons.DungeonFeature$Start.method_16655(DungeonFeature.java:39)
	at net.minecraft.class_3195.method_28657(class_3195.java:269)
	at net.minecraft.class_5312.method_28622(class_5312.java:36)
	at net.minecraft.class_2794.method_28508(class_2794.java:309)
	at net.minecraft.class_2794.method_16129(class_2794.java:292)
	at net.minecraft.class_2806.method_16556(class_2806.java:53)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)
	at net.minecraft.class_3898.method_17225(class_3898.java:555)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:549)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:131)
	at net.minecraft.class_3846.run(class_3846.java:99)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Andyghandi** [comment]
After removing charm, next structure mod (repurposed structures) seems to conflict with the same behavior. Is this mod incompatible with structure gen?

**Comment by Andyghandi** [comment]
I think I know what could be the issue. I'm using the new caves mod, which increases world height, and I guess this mod doesn't like those changes. Is there a possible fix to this?

**Comment by KdotJPG** [comment]
Good catch, I had not tried any mods that increase the world height. While the 1.17 Noise Cave features won't generate yet in this mod, it should still allow the world height to be configured, so I will get to fixing this!

**Comment by KdotJPG** [comment]
Should be working in the new release!
